export const strings = {
    logoMark: 'Laylo Tour Map',
    passwordPlaceholder: 'Enter password',
    passswordSubmitButtonText: 'Continue',
    incorrectPasswordErrorText: 'Incorrect password. Please Try Again',
    logoutButtonText: 'Logout',
    releaseNotesLinkText: 'Release Notes',
    releaseNotesSubtitle: "What's changed in Laylo Tour Map.",
    ticketBackLink: '← Back to map',
    ticketClaimHeading: 'Claim your ticket',
    ticketConfirmedHeading: "You're in!",
    ticketFreeLabel: 'Free',
    ticketClaimCta: 'Claim Free Ticket',
    ticketConfirmedLabel: 'Ticket confirmed',
    ticketNotFound: 'Show not found.',
    ticketGetTickets: 'Get Tickets →',
}