export const strings = {
    appName: 'Stagefinder',
    releaseNotesLinkText: 'Release Notes',
    releaseNotesSubtitle: "What's changed in Stagefinder.",
    sidebarHeading: 'Venues',
    payStructureLabel: 'Pay structure',
    payStructureLabels: {
        'free-exposure': 'Free / exposure only',
        'pay-to-play': 'Pay to play',
        'door-split': 'Door split',
        'guaranteed-fee': 'Guaranteed fee',
        'unknown': 'Unclear — confirm before booking',
    },
    capacityLabel: 'Capacity',
    genreFitLabel: 'Genre fit',
    equipmentProvidedLabel: 'Equipment provided',
    equipmentByoLabel: 'None — bring your own gear',
    curationNotesLabel: 'Curator notes',
    lastVerifiedLabel: 'Last verified',
    contactCallLabel: 'Call venue',
    contactEmailLabel: 'Email venue',
    contactUnavailableLabel: 'No contact info on file yet',
}
